### ISSUE TITLE
Easier to work with history vectors observations

### ISSUE THREAD

**Issue by berland** [equinor/fmu-ensemble#72]

**Comment by berland** [comment]
* [ ] Add doc on how to load observations from a yaml string - easier in notebooks compared to inputting the dict-list-dict structure.
* [ ] Guess `histvec` automatically, it does not need to be required for `smryh`
* [ ]  Fails hard on non-existing summary keys, should perhaps just warn about them
* [ ] Warnings from realization object should include the realization index.

**Comment by berland** [comment]
```
yamlobs = """
smryh:
  - key: WOPT:J-11BH
    histvec: WOPTH:J-11BH
    time_index: 2018-01-01
  - key: WOPT:J-14BH
    histvec: WOPTH:J-14BH
    time_index:
      - 2011-01-01
      - 2018-01-01
  - key: WOPT:J-13BH
    histvec: WOPTH:J-13BH
    time_index:
      - 2018-01-01
"""
obs = ensemble.Observations(yaml.safe_load(yamlobs))
```
